# apiVersion: apps/v1 (Does not exist)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-app-deploy
  labels:
    app: node-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-pod
        image: gcr.io/[GCLOUD_PROJECT]/node-image
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
